# mk9 -> mk10
#   Increased L1 regularization

# use null for random seed
seed: null
# Number of epochs to train
epoch: 10
# Batch size. You can try adjusting this for better hardware utilization
batch: 32
# If partial images should be treated as none when training
partial_as_none: True

# Add empty (fully white) pictures. This is a multiplier to total number of training images
augment_empty: 0.65

# Parameter for how much random translation used to augment the data. 0.05 = 5%
random_translation:
  height: 0.03
  width: 0.03

# Parameter for how much noise to add (standard deviation)
noise: 0.06

# Convolutional layers
convolution:
  # How many rounds of (convolution + max pooling)
  rounds: 2 # 2 is better than 1 or 3

  # How many features
  features: 16
  # regularization
  l1: 0.00015
  l2: 0.0006

# Dense layer
dense:
  # Number of neurons
  size: 288
  # regularization
  l1: 0.00015
  l2: 0.0006